name: Docker Build and Push on Merge

on:
    pull_request:
        types: [closed]
        branches:
            - main

jobs:
    build-and-push:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login no Docker Hub
              uses: docker/login-action@v3
              with:
                    username: luisffilho
                    password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and Push
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: |
                    luisffilho/chatmessapi:latest
                    luisffilho/chatmessapi:${{ github.sha }}
                
            - name: Notificar sucesso
              run: echo "Docker build e push finalizado com sucesso"